import { StyleSheet } from "react-native";
import { colors } from "../../constants/theme";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
    },
    content: {
      flex: 1,
      padding: 16,
      backgroundColor: colors.white,
      alignItems: "center",
      justifyContent: "flex-start",
      fontSize: 12,
      marginTop: 4,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: colors.white,
    },
    profileContainer: {
      marginTop: 50,
      marginBottom: 10,
      backgroundColor: colors.white,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: "auto",
      marginRight: "auto",
      borderRadius: 100,
      borderWidth: 1,
      borderColor: colors.white,
      elevation: 20,
      shadowColor: colors.white,
      shadowOffset: {
        width: 0,
        height: 10,
      },
      shadowOpacity: 0.58,
    },
    reportItemCarousel: {
      top: 0,
      marginTop: 70,
      marginBottom: "50%",
      justifyContent: "center",
      alignItems: "center",
      display: "flex",
      padding: 8,
      elevation: 20,
      shadowColor: colors.primary,
      shadowOffset: {
        width: 0,
        height: 10,
      },
      shadowOpacity: 0.58,
      shadowRadius: 16,
      borderWidth: 0,
      borderColor: "transparent",
      borderRadius: 10,
      backgroundColor: colors.primary,
      height: 400,
      width: 250,
    },
    reportContentCarousel: {
      marginTop: 15,
      marginBottom: "auto",
      marginLeft: "auto",
      marginRight: "auto",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    sectionWelcome: {
      fontSize: 18,
      fontWeight: "normal",
      fontFamily: "SourceSansPro_400",
      marginTop: "8%",
      position: "relative",
      marginBottom: 0,
      marginLeft: 20,
      color: colors.primary,
    },
    reportTextNameCarousel: {
      fontSize: 27,
      fontFamily: "SourceSansPro_700Bold",
      fontWeight: "bold",
      color: colors.white,
      marginTop: "auto",
      textAlign: "center",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      marginLeft: "auto",
      marginRight: "auto",
    },
    reportTextCarousel: {
      fontSize: 10,
      fontFamily: "SourceSansPro_700Bold",
      fontWeight: "bold",
      marginTop: 4,
      color: colors.white,
      position: "relative",
    },
    reportRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 4,
    },
    backgroundImage: {
      width: "100%",
      height: 60,
      resizeMode: "cover",
      justifyContent: "flex-start",
      alignSelf: "center",
    },
    carouselContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: "auto",
      marginBottom: "auto",
    },
    reportInfoContainer: {
      marginBottom: "auto",
      marginRight: 20,
      marginLeft: 20,
      margin: "auto",
      justifyContent: "flex-start",
      display: "flex",
      alignItems: "flex-start",
      right: 10,
      marginTop: 4,
    },
    reportTextInfo: {
      fontSize: 14,
      fontFamily: "SourceSansPro_700Bold",
      marginLeft: 8,
      color: colors.white,
    },
  });